### ISSUE TITLE
Weird overlays in GitHub View

### ISSUE THREAD

**Issue by wrygiel** [winterstein/Eclipse-Markdown-Editor-Plugin#78]
Recently I started to see weird text overlays over headers in my GitHub Flavored view:

![image](https://user-images.githubusercontent.com/2168535/30801649-3bfdb5ba-a1e4-11e7-96ac-3f9214a49455.png)

This started "on itself", without any action on my part. Perhaps caused by GitHub API change?

**Comment by wrygiel** [comment]
The problem seems to have fixed itself. Perhaps this was a temporary bug on GitHub's part.

**Comment by winterstein** [comment]
Hello Wojciech,

I'm glad to hear the issue has gone. Thank you for letting us know.

Kind regards,
Daniel


Sent from my phone. Please excuse the brevity.


On 26 Sep 2017 8:09 p.m., "Wojciech Rygielski" <notifications@github.com>
wrote:

The problem seems to have fixed itself. Perhaps this was a temporary bug on
GitHub's part.

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/winterstein/Eclipse-Markdown-Editor-Plugin/issues/78#issuecomment-332303621>,
or mute the thread
